authapp/urls.py
from django.conf.urls import url

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    url(r'^login/$', authapp.login, name='login'),
    url(r'^logout/$', authapp.logout, name='logout'),
    url(r'^register/$', authapp.register, name='register'),
    url(r'^edit/$', authapp.edit, name='edit'),
]

basket/urls.py
from django.conf.urls import url

import basket.views as basket

app_name = 'basket'

urlpatterns = [
    # url(r'^$', basket.BasketListView.as_view(), name='view'),
    url(r'^$', basket.basket, name='view'),
    # url(r'^add/(?P<pk>\d+)/$', basket.BasketAddView.as_view(), name='add'),
    url(r'^add/(?P<pk>\d+)/$', basket.basket_add, name='add'),
    # url(r'^remove/(?P<pk>\d+)/$', basket.BasketRemoveView.as_view(), name='remove'),
    url(r'^remove/(?P<pk>\d+)/$', basket.basket_remove, name='remove'),
    # url(r'^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$', basket.BasketUpdateView.as_view(), name='edit'),
    url(r'^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$', basket.basket_edit, name='edit'),
    url(r'^delete/(?P<pk>\d+)/$', basket.basket_delete, name='delete'),

]

myshop/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

import mainapp.views as mainapp

urlpatterns = [
    url(r'^$', mainapp.main, name='main'),
    url(r'^catalogue/', mainapp.catalogue, name='catalogue'),  # 16.09.19
    # url(r'^catalogue/', include('mainapp.urls', namespace='catalogue')),
    url(r'^contact/', mainapp.contact, name='contact'),
    url(r'^good/(\d+)/$', mainapp.good, name='good'),
    url(r'^auth/', include('authapp.urls', namespace='auth')),
    url(r'^basket/', include('basket.urls', namespace='basket')),
    url(r'^myadmin/', include('myadmin.urls', namespace='myadmin')),
    url(r'^search/$', mainapp.search, name='search'),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name='возраст')
    is_active = models.BooleanField(verbose_name='действительный', default=True)

authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from .models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        # fields = '__all__'
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super(ShopUserRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'email', 'age', 'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data

authapp/views.py
from django.contrib import auth
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse

from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm


# Create your views here.

# def login(request):
#     title = 'вход'
#     login_form = ShopUserLoginForm(data=request.POST or None)
#     if request.method == 'POST' and login_form.is_valid():
#         username = request.POST['username']
#         password = request.POST['password']
#
#         user = auth.authenticate(username=username, password=password)
#         if user and user.is_active:
#             auth.login(request, user)
#             return HttpResponseRedirect(reverse('main'))
#
#     content = {'title': title, 'login_form': login_form}
#     return render(request, 'authapp/login.html', content)

def login(request):
    # создать форму
    login_form = ShopUserLoginForm(data=request.POST or None)

    next = request.GET['next'] if 'next' in request.GET.keys() else ''
    # print('next', next)

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                # print('redirect next', request.POST['next'])
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('main'))

    content = {
        'login_form': login_form,
        'next': next
    }
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


def register(request):
    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegisterForm()

    content = {'register_form': register_form}

    return render(request, 'authapp/register.html', content)


def edit(request):
    title = 'редактирование'

    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)

    content = {'title': title, 'edit_form': edit_form}

    return render(request, 'authapp/edit.html', content)

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <title>PeterS Сognac Magazine (BoS example)</title>
    <link href="{% static 'css/style.css'%}" rel="stylesheet">
    {% block js %}

    {% endblock %}
</head>
<body>
<div class="container">
    <div class="login">
        <div class="h2 text-center head">
            Вход в систему
        </div>

        {% block content %}

        {% endblock %}
    </div>
</div>
</body>
</html>

authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}


{% block content %}
<form action="{% url 'auth:edit' %}" class="form-horizontal" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ edit_form.as_p }}
    <input class="form-control" type="submit" value="Сохранить">
</form>

<a class="btn_main" href="{% url 'main' %}"> На главную</a>

<div class="user_avatar"><img src="/media/{{ user.avatar|default:'users_avatars/default.jpg' }}"></div>
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}


{% block content %}
<form action="{% url 'auth:login' %}" class="form-horizontal" method="post">
    {% csrf_token %}
    {% if next %}
    <input name="next" type="hidden" value="{{ next }}">
    {% endif %}
    {{ login_form.as_table }}
    <br>
    <input class="form-control" type="submit" value="Вход">
</form>

<a class="btn_main" href="{% url 'auth:register' %}"> Регистрация</a>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}


{% block content %}
<form action="{% url 'auth:register' %}" class="form-horizontal" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ register_form.as_p }}
    <br>
    <input class="form-control" type="submit" value="зарегистрироваться">
</form>

{% endblock %}