basket/urls.py
from django.conf.urls import url

import basket.views as basket

app_name = 'basket'

urlpatterns = [
    # url(r'^$', basket.BasketListView.as_view(), name='view'),
    url(r'^$', basket.basket, name='view'),
    # url(r'^add/(?P<pk>\d+)/$', basket.BasketAddView.as_view(), name='add'),
    url(r'^add/(?P<pk>\d+)/$', basket.basket_add, name='add'),
    # url(r'^remove/(?P<pk>\d+)/$', basket.BasketRemoveView.as_view(), name='remove'),
    url(r'^remove/(?P<pk>\d+)/$', basket.basket_remove, name='remove'),
    # url(r'^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$', basket.BasketUpdateView.as_view(), name='edit'),
    url(r'^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$', basket.basket_edit, name='edit'),
    url(r'^delete/(?P<pk>\d+)/$', basket.basket_delete, name='delete'),

]

myadmin/urls.py
from django.conf.urls import url

import myadmin.views as myadmin

app_name = 'myadmin'

urlpatterns = [
    url(r'^users/create/$', myadmin.UserCreateView.as_view(), name='user_create'),
    url(r'^users/read/$', myadmin.UsersListView.as_view(), name='users'),
    url(r'^users/update/(?P<pk>\d+)/$', myadmin.UserUpdateView.as_view(), name='user_update'),
    url(r'^users/delete/(?P<pk>\d+)/$', myadmin.UserDeleteView.as_view(), name='user_delete'),

    # url(r'^countrys/$', myadmin.countrys, name='countrys'),
    url(r'^countrys/create/$', myadmin.CountryCreateView.as_view(), name='country_create'),
    url(r'^countrys/read/$', myadmin.CountrysListView.as_view(), name='countrys'),
    # url(r'^countrys/update/(?P<pk>\d+)/$', myadmin.CountryUpdateView.as_view(), name='country_update'),
    url(r'^countrys/update/(?P<pk>\d+)/$', myadmin.CountryCreateView.as_view(), name='country_update'),
    url(r'^countrys/delete/(?P<pk>\d+)/$', myadmin.CountryDeleteView.as_view(), name='country_delete'),

    # url(r'^products/create/country/(?P<pk>\d+)/$', myadmin.product_create, name='product_create'),
    url(r'^products/create/country/(?P<pk>\d+)/$', myadmin.ProductCreateView.as_view(), name='product_create'),
    # url(r'^products/read/country/(?P<pk>\d+)/$', myadmin.products, name='products'),
    url(r'^products/read/country/(?P<pk>\d+)/$', myadmin.CountryProductsView.as_view(), name='products'),
    url(r'^products/read/(?P<pk>\d+)/$', myadmin.ProductDetailView.as_view(), name='product_read'),
    url(r'^products/update/(?P<pk>\d+)/$', myadmin.ProductUpdateView.as_view(), name='product_update'),
    url(r'^products/delete/(?P<pk>\d+)/$', myadmin.ProductDeleteView.as_view(), name='product_delete'),
]

myshop/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

import mainapp.views as mainapp

urlpatterns = [
    url(r'^$', mainapp.main, name='main'),
    url(r'^catalogue/', mainapp.catalogue, name='catalogue'),  # 16.09.19
    # url(r'^catalogue/', include('mainapp.urls', namespace='catalogue')),
    url(r'^contact/', mainapp.contact, name='contact'),
    url(r'^good/(\d+)/$', mainapp.good, name='good'),
    url(r'^auth/', include('authapp.urls', namespace='auth')),
    url(r'^basket/', include('basket.urls', namespace='basket')),
    url(r'^myadmin/', include('myadmin.urls', namespace='myadmin')),
    url(r'^search/$', mainapp.search, name='search'),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myadmin/models.py
# Create your models here.

myadmin/forms.py
from django import forms

from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser
from mainapp.models import Country, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class CountryEditForm(forms.ModelForm):
    class Meta:
        model = Country
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CountryEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

myadmin/views.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from authapp.models import ShopUser
from mainapp.models import Country, Product


class UsersListView(ListView):
    model = ShopUser
    template_name = 'myadmin/users.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(UsersListView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UsersListView, self).get_context_data(**kwargs)
        context['title'] = 'админка/пользователи'
        return context


class UserCreateView(CreateView):
    model = ShopUser
    template_name = 'myadmin/user_update.html'
    success_url = reverse_lazy('myadmin:users')
    fields = ('__all__')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(UserCreateView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserCreateView, self).get_context_data(**kwargs)
        context['title'] = 'пользователи/создание'
        return context


class UserUpdateView(UpdateView):
    model = ShopUser
    template_name = 'myadmin/user_update.html'
    success_url = reverse_lazy('myadmin:users')
    fields = ('__all__')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(UserUpdateView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'пользователи/редактирование'
        return context


class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = 'myadmin/user_delete.html'
    success_url = reverse_lazy('myadmin:users')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(UserDeleteView, self).dispatch(*args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super(UserDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'пользователи/удаление'
        return context


################################################################

class CountrysListView(ListView):
    model = Country
    template_name = 'myadmin/countrys.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(CountrysListView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CountrysListView, self).get_context_data(**kwargs)
        context['title'] = 'админка/страны'
        return context


'''
@user_passes_test(lambda u: u.is_superuser)
def countrys(request):
    title = 'админка/страны'
    countrys_list = Country.objects.all()
    content = {
        'title': title,
        'objects': countrys_list
    }
    return render(request, 'myadmin/countrys.html', content)
'''


class CountryCreateView(CreateView):
    model = Country
    template_name = 'myadmin/country_update.html'
    success_url = reverse_lazy('myadmin:countrys')
    fields = ('__all__')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(CountryCreateView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CountryCreateView, self).get_context_data(**kwargs)
        context['title'] = 'страны/создание/редактирование'
        return context


'''
class CountryUpdateView(UpdateView):
    model = Country
    template_name = 'myadmin/country_update.html'
    success_url = reverse_lazy('myadmin:countrys')
    fields = ('__all__')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(CountryUpdateView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CountryUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'страны/редактирование'
        return context

'''


class CountryDeleteView(DeleteView):
    model = Country
    template_name = 'myadmin/country_delete.html'
    success_url = reverse_lazy('myadmin:countrys')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(CountryDeleteView, self).dispatch(*args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super(CountryDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'страны/удаление'
        return context


########################################################

'''
@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    title = 'админка/продукт'
    country = get_object_or_404(Country, pk=pk)
    products_list = Product.objects.filter(country__pk=pk).order_by('caption')
    print(products_list)
    content = {
        'title': title,
        'country': country,
        'objects': products_list,
    }
    return render(request, 'myadmin/products.html', content)

'''


class CountryProductsView(ListView):
    template_name = 'myadmin/products.html'

    def get_queryset(self):
        pk = self.kwargs['pk']
        print(self.request, self.kwargs)
        self.country = get_object_or_404(Country, pk=pk)
        print('1pk', pk)
        products_list = Product.objects.filter(country__pk=pk)
        print('1pl', products_list)
        return products_list

    def get_context_data(self, **kwargs):
        context = super(CountryProductsView, self).get_context_data(**kwargs)
        print('1c1', context)
        context['title'] = 'продукт/создание'
        pk = self.kwargs['pk']
        context['country'] = self.country
        print('1c2', context)
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'myadmin/product_read.html'


class ProductCreateView(CreateView):
    model = Product
    template_name = 'myadmin/product_create.html'
    fields = ('__all__')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(ProductCreateView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProductCreateView, self).get_context_data(**kwargs)
        # print('c1',context)
        context['title'] = 'продукт/создание'
        pk = self.kwargs['pk']
        self.country = get_object_or_404(Country, pk=pk)
        print(self.country)
        print('c2', context)
        print(pk)
        context['pk'] = pk
        return context

    def get_success_url(self):
        # return reverse('myadmin:products', args=[self.object.country.pk])
        return reverse('myadmin:products', args=[self.kwargs['pk']])
        # return reverse('myadmin:products', args=[2])


class ProductUpdateView(UpdateView):
    model = Product
    template_name = 'myadmin/product_update.html'
    fields = ('__all__')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(ProductUpdateView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProductUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'продукт/редактирование'
        pk = self.kwargs['pk']
        print(pk)
        self.country = get_object_or_404(Country, pk=pk)
        context['pk'] = pk
        return context

    def get_success_url(self):
        return reverse('myadmin:products', args=[self.kwargs['pk']])
        # return reverse('myadmin:products', args=[self.object.country.pk])
        # return reverse('myadmin:products', args=[self.country.pk])
        # return reverse('myadmin:products', args=[1])


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'myadmin/product_delete.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(ProductDeleteView, self).dispatch(*args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super(ProductDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'продукт/удаление'
        pk = self.kwargs['pk']
        print(pk)
        context['pk'] = pk
        return context

    def get_success_url(self):
        return reverse('myadmin:products', args=[self.kwargs['pk']])
        # return reverse('myadmin:products', args=[self.object.country.pk])


'''
@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    title = 'админка/продукт'
    country = get_object_or_404(Country, pk=pk)
    products_list = Product.objects.filter(country__pk=pk).order_by('caption')
    content = {
        'title': title,
        'country': country,
        'objects': products_list,
    }

myadmin/templates/myadmin/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<h2> Админка </h2>
{% block menu %}
<div class="myadmin_container admin_menu">
    {% include 'myadmin/includes/inc_menu.html' %}
</div>
{% endblock %}


{% block content %}

{% endblock %}

</body>
</html>

myadmin/templates/myadmin/country_delete.html
{% extends 'myadmin/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="myadmin_container country_delete">
    Уверены, что хотите удалить страну <strong>{{ object.name }}</strong>?
    <form action="{% url 'myadmin:country_delete' object.pk %}" method="post">
        {% csrf_token %}
        <input class="btn" type="submit" value="Удалить">
    </form>
    <a class="btn" href="{% url 'myadmin:countrys' %}">Отмена</a>
</div>
{% endblock %}

myadmin/templates/myadmin/country_update.html
{% extends 'myadmin/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="myadmin_container new_category_form">
    <form class="form-horizontal" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="Сохранить">
    </form>
    <a class="btn_main" href="{% url 'myadmin:countrys' %}">
        К списку стран
    </a>
</div>
{% endblock %}

myadmin/templates/myadmin/countrys.html
{% extends 'myadmin/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="myadmin_container countrys_list">
    <a class="btn new" href="{% url 'myadmin:country_create' %}">Новая страна</a>
    {% for object in object_list %}
    <div class="country_record {% if not object.is_active %} not_active {% endif %}">

        <div class="country_name">
            {{ object.name|title }}
        </div>
        <div class="country_actions">
            <a class="btn" href="{% url 'myadmin:products' object.pk %}">Продукты страны</a>
            <a class="btn" href="{% url 'myadmin:country_update' object.pk %}">Редактировать</a>
            <a class="btn" href="{% url 'myadmin:country_delete' object.pk %}">Удалить</a>
        </div>
        <div class="country_desc">
            {{ object.description|title }}
        </div>
    </div>
    <hr>
    {% endfor%}
</div>
{% endblock %}

myadmin/templates/myadmin/product_create.html
{% extends 'myadmin/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="myadmin_container new_category_form">
    <form class="form-horizontal" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="Сохранить">
    </form>
    <a class="btn_main" href="{% url 'myadmin:products' pk %}">
        К списку продуктов
    </a>
</div>
{% endblock %}

myadmin/templates/myadmin/product_delete.html
{% extends 'myadmin/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="myadmin_container product_delete">
    Уверены, что хотите удалить продукт <strong>{{ object.caption }}</strong>?
    <form action="{% url 'myadmin:product_delete' pk %}" method="post">
        {% csrf_token %}
        <input class="btn" type="submit" value="Удалить">
    </form>
    <a class="btn" href="{% url 'myadmin:products' pk %}">
        Отмена
    </a>
</div>
{% endblock %}

myadmin/templates/myadmin/product_read.html
{% extends 'myadmin/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="myadmin_container product_read">
    <div class="product_name">
        Продукт<strong>{{ object.country.caption|title }} / {{ object.caption }}</strong>
    </div>
    <img alt="{{ object.caption }}" class="img_g"
         src="/media/{{ object.image_src|default:'products_images/default.jpg' }}">
    <div class="summary">
        <p>
            <b>Цена: </b>{{ object.cost }} руб.
        </p>
        <p>
            <b>Количество: </b>{{ object.quantity }} шт.
        </p>
        <b>В каталоге </b>{% if object.is_active %}имеется{% else %}отсутствует{% endif %}
        <p>
            <a class="btn" href="{% url 'myadmin:product_update' object.pk %}">Редактировать</a>
        </p>
        <p>
            <a class="btn" href="{% url 'myadmin:product_delete' object.pk %}">Удалить</a>
        </p>
        <p>
            <a class="btn" href="{% url 'myadmin:products' object.country.pk %}">Назад</a>
        </p>
    </div>
    <div class="product_desc">
        <b>Краткая характеристика:</b>
        <p>
            {{ object.quality }}
        </p>
        <b>Подробная информация:</b>
        <p>
            {{ object.comment }}
        </p>
    </div>
</div>
{% endblock %}

myadmin/templates/myadmin/product_update.html
{% extends 'myadmin/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="myadmin_container new_category_form">
    <form class="form-horizontal" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="Сохранить">
    </form>
    <a class="btn_main" href="{% url 'myadmin:products' pk %}">
        К списку продуктов
    </a>
</div>
{% endblock %}

myadmin/templates/myadmin/products.html
{% extends 'myadmin/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="myadmin_container products_list">
    <a class="btn new" href="{% url 'myadmin:product_create' country.pk %}">Новый продукт</a>

    {% for object in object_list %}
    <div class="product_record {% if not object.is_active %} not_active {% endif %}">
        <div class="product_actions">
            <a class="btn" href="{% url 'myadmin:product_read' object.pk %}">Подробнее</a>
            <a class="btn" href="{% url 'myadmin:product_update' object.pk %}">Редактировать</a>
            <a class="btn" href="{% url 'myadmin:product_delete' object.pk %}">Удалить</a>
        </div>
        <img alt="{{ object.caption }}" src="/media/{{ object.image_src|default:'products_images/default.jpg' }}">
        <div class="product_name">
            {{ object.caption|title }}
        </div>
        <div class="summary">
            <b>Цена: </b>{{ object.cost }} руб.
            <b>Количество: </b>{{ object.quantity }} шт.
        </div>
        <div class="product_desc">
            {{ object.comment }}
        </div>
    </div>
    <hr>
    {% endfor%}
</div>
{% endblock %}

myadmin/templates/myadmin/user_delete.html
{% extends 'myadmin/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="myadmin_container user_delete">
    Уверены, что хотите удалить <b>{{ object.username }}</b>{% if object.first_name %}
    ({{ object.first_name|title }}
    {% if object.last_name %}
    {{ object.last_name|title }}
    {% endif %})
    {% endif %}?
    <form action="{% url 'myadmin:user_delete' object.pk %}" method="post">
        {% csrf_token %}
        <input class="btn" type="submit" value="Удалить">
    </form>
    <a class="btn" href="{% url 'myadmin:users' %}">Отмена</a>
</div>
{% endblock %}

myadmin/templates/myadmin/user_update.html
{% extends 'myadmin/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="myadmin_container new_user_form">
    <form class="form-horizontal" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <a class="btn_main" href="{% url 'myadmin:users' %}">
        К списку пользователей
    </a>
</div>
{% endblock %}

myadmin/templates/myadmin/users.html
{% extends 'myadmin/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="myadmin_container users_list">
    <a class="btn new" href="{% url 'myadmin:user_create' %}">Новый пользователь</a>
    {% for object in object_list %}
    <div class="user_record {% if not object.is_active %}not_active{% endif %}">
        <div class="user_actions">
            {% if object.is_superuser %}Администратор{% else %}Пользователь{% endif %}
            <a class="btn" href="{% url 'myadmin:user_update' object.pk %}">Редактировать</a>
            <a class="btn" href="{% url 'myadmin:user_delete' object.pk %}">Удалить</a>
        </div>
        <img alt="{{ object.username }}" src="/media/{{ object.avatar|default:'users_avatars/default.jpg' }}">

        <div class="user_name">
            <strong>{{ object.username }}:</strong>
            {% if object.first_name %}
            <b>{{ object.first_name|title }}</b>
            {% if object.last_name %}
            {{ object.last_name|title }}
            {% endif %}
            {% endif %}
        </div>
        <div class="user_age">
            age: {{ object.age }} лет
        </div>
        <div class="user_email">
            email: {{ object.email }}
        </div>
        <div class="user_lastlogin">
            logged: {{ object.last_login }}
        </div>
    </div>
    <hr>
    {% endfor%}
</div>
{% endblock %}