basket/urls.py
from django.conf.urls import url

import basket.views as basket

app_name = 'basket'

urlpatterns = [
    # url(r'^$', basket.BasketListView.as_view(), name='view'),
    url(r'^$', basket.basket, name='view'),
    # url(r'^add/(?P<pk>\d+)/$', basket.BasketAddView.as_view(), name='add'),
    url(r'^add/(?P<pk>\d+)/$', basket.basket_add, name='add'),
    # url(r'^remove/(?P<pk>\d+)/$', basket.BasketRemoveView.as_view(), name='remove'),
    url(r'^remove/(?P<pk>\d+)/$', basket.basket_remove, name='remove'),
    # url(r'^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$', basket.BasketUpdateView.as_view(), name='edit'),
    url(r'^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$', basket.basket_edit, name='edit'),
    url(r'^delete/(?P<pk>\d+)/$', basket.basket_delete, name='delete'),

]

mainapp/urls.py
from django.conf.urls import url

import mainapp.views as mainapp

# обязательно указывать для django 2.0
app_name = 'mainapp'

urlpatterns = [
    url(r'^$', mainapp.catalogue),  # 16.09.19
    # url(r'^(\d+)/$', mainapp.good, name='good'),
    # url(r'^country/(\d+)/$', mainapp.country, name='country'),
    # url(r'^country/(?P<count_pk>\d+)/page/(?P<page>\d+)/$', mainapp.catalogue, name='country_catalogue'),
    # url(r'^country/(?P<count_pk>\d+)/page/(?P<page>\d+)/$', mainapp.catalogue, name='country_catalogue'),
    # 16.09.19
    # url(r'^country/(?P<pk>\d+)/$', mainapp.catalogue, name='country'),
    # url(r'^country/(?P<pk>\d+)/page/(?P<page>\d+)/$', mainapp.catalogue, name='page'),
    # url(r'^page/(?P<page>\d+)/$', mainapp.catalogue, name='page'),
    # url(r'^rating/(\d+)/$', mainapp.product_rating_accounting, name='rating'),
]

myshop/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

import mainapp.views as mainapp

urlpatterns = [
    url(r'^$', mainapp.main, name='main'),
    url(r'^catalogue/', mainapp.catalogue, name='catalogue'),  # 16.09.19
    # url(r'^catalogue/', include('mainapp.urls', namespace='catalogue')),
    url(r'^contact/', mainapp.contact, name='contact'),
    url(r'^good/(\d+)/$', mainapp.good, name='good'),
    url(r'^auth/', include('authapp.urls', namespace='auth')),
    url(r'^basket/', include('basket.urls', namespace='basket')),
    url(r'^myadmin/', include('myadmin.urls', namespace='myadmin')),
    url(r'^search/$', mainapp.search, name='search'),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models

from authapp.models import ShopUser


# Create your models here.
class Country(models.Model):
    name = models.CharField(verbose_name='страна изготовления', max_length=64, unique=True)
    is_active = models.BooleanField(verbose_name='действительная', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name='страна изготовления')
    caption = models.CharField(verbose_name='название продукта', max_length=128, unique=True)
    quality = models.TextField(verbose_name='признаки продукта', blank=True)
    preference = models.TextField(verbose_name='применение продукта', blank=True)
    image_src = models.ImageField(upload_to='products_images', blank=True)
    producer = models.CharField(verbose_name='организация - изготовитель продукта', max_length=60, blank=True)
    brand = models.CharField(verbose_name='фирменный знак продукта', max_length=60, blank=True)
    alco = models.CharField(verbose_name='крепкость продукта', max_length=60, blank=True)
    vol = models.CharField(verbose_name='объем продукта', max_length=5, blank=True)
    class_c = models.CharField(verbose_name='класс продукта', max_length=10, blank=True)
    age = models.IntegerField(verbose_name='возраст продукта', null=True)
    cost = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    comment = models.TextField(verbose_name='описание продукта', blank=True)
    is_active = models.BooleanField(verbose_name='действительный', default=True)

    def __str__(self):
        return "{} ({})".format(self.caption, self.country.name)


class Rating(models.Model):
    RATING = ((0, 'отсутствует'), (1, 'неуд'), (2, 'удовл'), (3, 'хор'), (4, 'отл'))
    rating = models.IntegerField(choices=RATING, default=0, db_index=True,
                                 verbose_name='рейтинг продукта от пользователя')
    rating_product = models.OneToOneField(Product, on_delete=models.PROTECT, unique=False)
    rating_user = models.ManyToManyField(ShopUser, unique=False)

    def __str__(self):
        return str(self.rating)

mainapp/forms.py
from django import forms

from mainapp.models import Country

RATING_CHOICES = (
    (0, 'нет оценки'),
    (1, 'неудовлетворительно'),
    (2, 'удовлетворительно'),
    (3, 'хорошо'),
    (4, 'отлично'),
)

SORTING_CHOICES = (
    (0, 'по убыванию'),
    (1, 'по возрастанию'),
)

ATTRIBUTE_CHOICES = (
    (1, 'по цене'),
    (2, 'по рейтингу'),
)

COUNTRY_CHOICES = [(0, 'Все страны')]
country_list = [(i.id, i.name) for i in Country.objects.filter(is_active=True)]
COUNTRY_CHOICES.extend(country_list)
tuple(COUNTRY_CHOICES)
print(COUNTRY_CHOICES)


class ProdRatingForm(forms.Form):
    rating = forms.ChoiceField(choices=RATING_CHOICES, widget=forms.RadioSelect(),
                               initial=0, label='Выберите из списка:')


class SearchForm(forms.Form):
    search = forms.CharField(initial='', label='', required=False)


class ProdSortForm(forms.Form):
    country = forms.ChoiceField(choices=COUNTRY_CHOICES, label='Страны')
    # country = forms.ModelChoiceField(queryset=Country.objects.filter(is_active=True), label='Страны', empty_label='Все страны')
    price_rating = forms.ChoiceField(choices=ATTRIBUTE_CHOICES, initial=0, label='Цена/Рейтинг')
    sorting_direction = forms.ChoiceField(choices=SORTING_CHOICES, initial=0, label='По убыванию/возрастанию')

mainapp/views.py
import datetime
import json
import os
import random

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import models
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse

from authapp.models import ShopUser
from basket.models import Basket
from mainapp.forms import ProdRatingForm, SearchForm, ProdSortForm
from mainapp.models import Country, Product, Rating

JSON_PATH = 'mainapp/json'


def loadFromJSON(file_name):
    with open(os.path.join(JSON_PATH, file_name + '.json'), 'r') as infile:
        return json.load(infile)


# Create your views here.
def main(request):
    basket = getBasket(request.user)
    # content = {'links_menu': links_menu, 'basket': basket}
    content = {'basket': basket}

    return render(request, 'mainapp/index.html', content)


def getBasket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def getHotProduct():
    products = Product.objects.exclude(is_active=False).order_by('id')
    return random.sample(list(products), 1)[0]


def getSameProducts(hot_product, sort_variant=0, reverse=0):
    print('getSameProducts:', sort_variant, reverse)
    # same_products = Product.objects.exclude(pk=hot_product.pk).filter(is_active=True).order_by('id')
    # Вариант сортировки
    if sort_variant == 0:  # по умолчанию
        sv = 'id'
    elif sort_variant == 1:  # по цене
        sv = 'cost'
    else:  # по рейтингу
        # sv = 'rating'
        sv = 'age'
    # Направление сортировки
    if not reverse:  # 0 - по убыванию (по умолчанию)
        same_products = Product.objects.exclude(pk=hot_product.pk).filter(is_active=True).order_by(sv).reverse()
    else:  # 1 - по возрастанию
        same_products = Product.objects.exclude(pk=hot_product.pk).filter(is_active=True).order_by(sv)
    return same_products


def getSearchProduct(search):
    search_products = Product.objects.exclude(is_active=False).order_by('id').filter(caption__icontains=search)
    return search_products


def search(request):
    basket = getBasket(request.user)

    # Результат поиска
    form = SearchForm()
    search_query = request.GET.get('search', '')
    if search_query != '':
        # Товар найден...
        search_product = getSearchProduct(search_query)
        print('начало постраничного цикла ', search_query, search_product)

        # экземпляр класса Paginator (2 - объектов на странице)
        paginator = Paginator(search_product, 2)
        print('paginator in')
        print(request.GET.dict())
        page = request.GET.get('page', 1)
        print('номер текущей страницы с сайта =', page)

        try:
            # получение объектов нужной сраницы
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            # последняя страница
            products_paginator = paginator.page(paginator.num_pages)
        print('всего страниц пагинатора =', paginator.num_pages)
        print('номер текущей страницы пагинатора =', products_paginator.number)
        print('всего объектов в пагинаторе =', paginator.count)
        print('объекты в пагинаторе ->', products_paginator.object_list)
        print('paginator out')
        search_product = products_paginator

        content = {
            'search_query': search_query,
            'same_products': search_product,
            'page': page,
            'basket': basket,
            'form': form,
        }

    else:
        # Товар не найден...
        content = {
            'same_products': 0,
            'basket': basket,
            'form': form,
        }

    return render(request, 'mainapp/search.html', content)


# def catalogue(request, pk=0, page=1):
def catalogue(request):
    print('request - параметры запроса')
    print(request.GET.dict())
    try:
        # получение объектов запроса
        print('получение страны из запроса')
        pk = request.GET.get('country')
        pk = int(pk)
    except:
        print('сбой получения страны из запроса')
        pk = 0
    print('страна из запроса -> ', pk)

    try:
        # получение объектов запроса
        print('получение страницы из запроса')
        page = request.GET.get('page')
        page = int(page)
    except:
        print('сбой получения страницы из запроса')
        page = 1
    print('страница из запроса -> ', pk)

    # Добавляем форму выбора страны и сортировки товаров в шаблон
    form = ProdSortForm()

    # Читаем данные из формы ?
    if form.is_valid():
        pk = int(form.cleaned_data['country'])  # страна
        sv = int(form.cleaned_data['price_rating'])  # вариант сортировки (1 - по цене/2 - рейтингу)
        r = int(form.cleaned_data['sorting_direction'])  # 0 - убывание/1 - возрастание
        print('страна {}, поле сортировки {},  убыв/возр {} из формы -> '.format(pk, sv, r))

    # Читаем данные из запроса
    try:
        # получение объектов запроса
        print('получение вида сортировки из запроса')
        sv = request.GET.get('price_rating')
        sv = int(sv)
    except:
        print('сбой получения вида сортировки из запроса')
        # параметры сортировки по умолчанию
        sv = 0  # по id продукта
    print('вид сортировки  из запроса -> ', sv)

    try:
        # получение объектов запроса
        print('получение направления сортировки из запроса')
        r = request.GET.get('sorting_direction')
        r = int(r)
    except:
        print('сбой получения направления сортировки из запроса')
        # параметры сортировки по умолчанию
        r = 1  # возрастание
    print('направление сортировки из запроса -> ', r)

    basket = getBasket(request.user)

    # Формируем список товаров с учетом сортировки
    # countrys = Country.objects.filter(is_active=True)
    hot_product = getHotProduct()

    same_products = getSameProducts(hot_product, sv, r)

    print('список всех товаров, кроме горячего ->', same_products)

    if pk:
        country = get_object_or_404(Country, pk=pk)
        same_products = same_products.filter(country=pk).order_by('id')
        print('список товаров страны {} -> {}'.format(country, same_products))

    else:
        country = {
            'pk': 0,
            'name': 'Все'
        }
        print('список товаров страны {} -> {}'.format(country['name'], same_products))

    # экземпляр класса Paginator (2 - объектов на странице)
    paginator = Paginator(same_products, 2)
    print('paginator in')
    try:
        # получение объектов нужной сраницы
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        # последняя страница
        products_paginator = paginator.page(paginator.num_pages)
    print('всего страниц пагинатора =', paginator.num_pages)
    print('номер текущей страницы =', products_paginator.number)
    print('всего объектов в пагинаторе =', paginator.count)
    print('объекты в пагинаторе ->', products_paginator.object_list)
    print(page)
    print('paginator out')

    # same_products = products_paginator

    content = {
        'page': page,
        'hot_product': hot_product,
        # 'same_products': same_products,
        'same_products': products_paginator,
        'basket': basket,
        'country': country,
        # 'countrys': countrys,
        'form': form,
        'price_rating': sv,
        'sorting_direction': r
    }
    return render(request, 'mainapp/catalogue.html', content)


def contact(request):
    visit_date = datetime.datetime.now()
    # content = {'links_menu': links_menu, 'visit_date': visit_date}
    content = {'visit_date': visit_date}

    return render(request, 'mainapp/contact.html', content)


def country(request, pk=None):
    basket = getBasket(request.user)
    countrys = Country.objects.all()
    # country = get_object_or_404(Country, pk=int(pk))
    products = Product.objects.filter(country__pk=pk).order_by('caption')
    content = {
        'countrys': countrys,
        'products': products,
        'basket': basket
    }
    return render(request, 'mainapp/country.html', content)


def good(request, pk=None):
    print('good', pk)
    basket = getBasket(request.user)
    countrys = Country.objects.all()
    same_product = Product.objects.get(pk=pk)

    print(request.META.get('HTTP_REFERER'))

    # Рейтинг продукта

    # Считаем усредненный рейтинг продукта по частным оценкам пользователей
    rfp = Rating.objects.filter(rating_product_id=pk)
    lrfp = len(rfp)  # число частных оценок продукта
    print('lrfp =', lrfp)
    r_product = 0

    if lrfp:
        r_product = rfp.aggregate(models.Avg('rating'))['rating__avg']
        print('r_product', r_product)
        if r_product == 4:
            rating_product = 'отлично'
        elif r_product >= 3:
            rating_product = 'хорошо'
        elif r_product >= 2:
            rating_product = 'удовлетворительно'
        else:
            rating_product = 'неудовлетворительно'

    else:
        rating_product = 'не оценен'

    user = request.user
    u_is_auth = user.is_authenticated
    print(u_is_auth)

    get_form = False
    form = None

    if u_is_auth:
        is_app = is_appreciated(id_product=pk, id_user=user.id)
        print('is_app', is_app)
        # if not lrfp or not is_app:
        if not is_app:
            # Предоставить форму для оценки продукта (на шаблоне)
            get_form = True
            form = ProdRatingForm(data=request.POST)
            # Запись рейтинга продукта pk от пользователя id_user в БД
            print('запись рейтинга для продукта {}... '.format(pk))
            print(request.method)
            print(form.is_valid())
            # if request.method == 'POST':
            # form = ProdRatingForm(request.POST)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ru">
<head>
    <meta charset="utf-8">
    <title>PeterS Сognac Magazine</title>
    <link href="{% static 'css/style.css'%}" rel="stylesheet">
    <link href="{% static 'img/favicon.ico' %}" rel="icon" type="image/x-icon"/>
    <link href="{% static 'img/favicon.ico' %}" rel="shortcut icon" type="image/x-icon"/>
    <link crossorigin="" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          rel="stylesheet"/>
    <script crossorigin=""
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"></script>


    {% block js %}

    {% endblock %}
</head>
<body>
<!-- Выполнил Стащук Петр -->
<div class="container">

    {% include 'mainapp/includes/inc_header.html' %}

    {% block add %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    <div class="footer">
        <p> {% now 'Y' %} &copy; «Все права защищены»</p>
    </div>
</div>

</body>
</html>

mainapp/templates/mainapp/catalogue.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load my_tags %}


{% block add %}

{% endblock %}

{% block content %}
<div class="content">

    <div class="subtitul">
        <h1 class="red">Горячее предложение</h1>
        <div class="hot">
            <p>
                <img alt="{{ hot_product.caption }}" height="72" src="/media/{{ hot_product.image_src }}" width="54">
            </p>
            <p>
                <a href="/good/{{ hot_product.id }}/"> {{ hot_product.caption|expanded_text }} </a>
            </p>
            <p class="price"> {{ hot_product.cost|ruble_penny }}</p>
        </div>
    </div>
    <h1> Сводный каталог коньяков:</h1>

    {% include 'mainapp/includes/inc_sorting.html' %}

    <div class="paginator">
        {% if same_products.has_previous %}
        <a href="/catalogue/?country={{ country.pk }}&page={{ same_products.previous_page_number }}
						&price_rating={{ price_rating }}&sorting_direction={{ sorting_direction }}"><</a>
        {% endif %}
        <span class="current">
			страница {{ same_products.number }} из {{ same_products.paginator.num_pages }}
			</span>
        {% if same_products.has_next %}
        <a href="/catalogue/?country={{ country.pk }}&page={{ same_products.next_page_number }}
						&price_rating={{ price_rating }}&sorting_direction={{ sorting_direction }}">></a>
        {% endif %}
    </div>

    <h2 class="subtitul"> {{ country.name }}</h2>
    <div class="catalog">
        {% for prod in same_products %}
        <div class="goods">
            <p>
                <img alt="{{ prod.caption }}" height="72" src="/media/{{ prod.image_src }}" width="54">
            </p>
            <p>
                <a href="/good/{{ prod.id }}/"> {{ prod.caption }} </a>
            </p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block content %}
<h3>Сегодня, {{ visit_date|title }} </h3>
<div class="form-cont">
    <form role="form">
        <div class="form-group col-lg-4 col-md-4">
            <h3>Напишите нам...</h3>
            <input class="form-control" placeholder="Введите Ваше имя" type="text">
            <input class="form-control" placeholder="Введите Ваш E-mail адрес" type="email">
            <input class="form-control" placeholder="Обозначьте тему Вашего сообщения" type="text">
            <p>Ваш возраст:</p>
            <select class="form-control">
                <option>23</option>
                <option>24</option>
                <option>25</option>
                <option>26</option>
                <option>27</option>
            </select>
            <div class="radio">
                <p>Ваш пол:</p>
                <label>
                    <input checked id="optionsRadios1" name="optionsRadios" type="radio" value="option1">М
                </label>
            </div>
            <div class="radio">
                <label>
                    <input id="optionsRadios2" name="optionsRadios" type="radio" value="option2">Ж
                </label>
            </div>
            <button class="btn btn-primary" type="submit">Отправить</button>
        </div>
    </form>

    <div class="row col-lg-4 col-md-4">
        <h3> Наши контакты: </h3>
        <address>
            <abbr title="">Телефон:</abbr> (123) 456-7890
            <strong>&laquo;PeterS Сognac Magazine&raquo;</strong><br>
            Адрес: Россия<br>
            Сайт: ...<br>
            E-mail: qq@qq<br>
        </address>
    </div>
    <div class="row col-lg-4 col-md-4">
        <h3>Наше расположение...</h3>
        <div id="mapid" style="width: 600px; height: 400px;"></div>
    </div>
</div>
<script>
	var mymap = L.map('mapid').setView([55.753323, 37.616544], 15);

	L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
		maxZoom: 18,
		attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
			'<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
			'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
		id: 'mapbox.streets'
	}).addTo(mymap);

	L.marker([55.753178, 37.618818]).addTo(mymap)
		.bindPopup("Добро пожаловать в<br/> <b>PeterS Сognac Magazine</b>!").openPopup();

	var popup = L.popup();

	function onMapClick(e) {
		popup
			.setLatLng(e.latlng)
			.setContent("You clicked the map at " + e.latlng.toString())
			.openOn(mymap);
	}

	mymap.on('click', onMapClick);





</script>

{% endblock %}

mainapp/templates/mainapp/country.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block add %}
{% include 'mainapp/includes/inc_country_menu.html' %}
{% endblock %}

{% block content %}

<div class="content">
    <h1> {{ country.name }}</h1>
    <div class="catalog">
        {% for prod in products %}
        <div class="goods">
            <p>
                <img alt="{{ prod.caption }}" height="72" src="/media/{{ prod.image_src }}" width="54">
            </p>
            <p>
                <a href="/good/{{ prod.id }}/"> {{ prod.caption }} </a>
            </p>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

mainapp/templates/mainapp/good.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block content %}
{% include 'mainapp/includes/inc_country_menu.html' %}

<h1>{{ same_product.caption }}</h1>
<h2 class="title"> Описание</h2>
<p class="small_img">
    <a href="/media/{{ same_product.image_src }}" target="_blank">
        <img alt="{{ same_product.caption }}" class="img_g" src="/media/{{ same_product.image_src }}">
        <!-- <img class="img_g" src="/static/img/Ararat_Akhtamar_10.jpg" alt="Коньяк Ахтамар (в подарочной коробке)">-->
    </a>
</p>
<p class="par">{{ same_product.quality }}</p>
<p class="par">{{ same_product.preference }}</p>
<form action="{% url 'basket:add' same_product.pk %}" method="post">
    {% csrf_token %}
    <button class="btn btn-primary btn_good" type="submit">Купить</button>
</form>

<h2 class="title"> Характеристики</h2>
<ul class="atribute">
    <li><b>Регион:</b> {{ same_product.country.name }}</li>
    <li><b>Производитель:</b> {{ same_product.producer }}</li>
    <li><b>Бренд:</b> {{ same_product.brand }}</li>
    <li><b>Крепость:</b> {{ same_product.alco }}</li>
    <li><b>Объем:</b> {{ same_product.vol }}</li>
    <li><b>Класс коньяка:</b> {{ same_product.class_c }}</li>
    <li><b>Выдержка:</b> {{ same_product.age }}&nbspлет</li>
    <li><b>Цена:</b> {{ same_product.cost }}&nbspруб.</li>
    <li><b>Количество (в наличие):</b> {{ same_product.quantity }}&nbspшт.</li>
</ul>
<h2 class="title"> Комментарии </h2>
<p class="par-text">{{ same_product.comment }}</p>
<h2 class="title"> Средняя оценка продукта покупателями </h2>
<p class="par-text">{{ rating_product }} ({{ r_product }})</p>
<h2 class="title"> Памятка </h2>
<p>Чрезмерное употребление алкоголя вредит вашему здоровью</p>
{% if get_form %}
{% include 'mainapp/includes/inc_good_rating.html' %}
{% endif %}
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block content %}
<h3> Магазин "Коньячный вкус" </h3>
<h5> Вы уже пробовали коньяк? Этот глубокий, насыщенный и элегантный напиток станет великолепным подарком для всех, кто
    ценит красоту, творчество и подлинное искусство. </h5>
<h3> Выбирайте вместе с нами. Покупайте у нас! </h3>
{% endblock %}

mainapp/templates/mainapp/search.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load my_tags %}

{% block content %}
<div class="content">
    <h1> Поиск продукта </h1>
    <form action="{% url 'search' %}" class="search" method="get">
        {{ form.as_p }}
        <button class="btn " type="submit">Искать</button>
    </form>

    {% if same_products %}
    <div class="paginator">
        {% if same_products.has_previous %}
        <a href="?search={{ search_query }}&page={{ same_products.previous_page_number }}"><</a>
        {% endif %}
        <span class="current">
				страница {{ same_products.number }} из {{ same_products.paginator.num_pages }}
				</span>
        {% if same_products.has_next %}
        <a href="?search={{ search_query }}&page={{ same_products.next_page_number }}">></a>
        {% endif %}
    </div>

    <h2 class="subtitul"> {{ country.name }}</h2>
    <div class="catalog">
        {% for prod in same_products %}
        <div class="goods">
            <p>
                <img alt="{{ prod.caption }}" height="72" src="/media/{{ prod.image_src }}" width="54">
            </p>
            <p>
                <a href="/good/{{ prod.id }}/"> {{ prod.caption }} </a>
            </p>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}